import type { LinguistAttributes } from './gitattributes.js';
import { linguistAttributesFor } from './gitattributes.js';
import type { NoiseAssessment, NoiseLabel, Part } from './protocol.js';

/**
 * The noise rules: each file gets one label — lockfile, generated,
 * vendored, moved or renamed, snapshot, fixture — or none, and every label
 * states whether it was confirmed or claimed and its one-line blind spot.
 *
 * Labels come from rules in a fixed order, and the first match wins: the
 * rename check outranks everything because it is the only confirmed one,
 * and a renamed snapshot or fixture keeps that label so it is never
 * sunk; the snapshot and fixture rules come next so a behaviour-changing
 * file is never relabelled by a sinking rule; then the repository's own
 * linguist declaration; then the name and header rules for generated
 * output and lockfiles.
 */

/** Lock file and checksum file basenames across the common ecosystems. */
const LOCKFILE_BASENAMES: ReadonlySet<string> = new Set([
  'package-lock.json',
  'npm-shrinkwrap.json',
  'yarn.lock',
  'pnpm-lock.yaml',
  'bun.lock',
  'bun.lockb',
  'Gemfile.lock',
  'Cargo.lock',
  'go.sum',
  'go.work.sum',
  'composer.lock',
  'poetry.lock',
  'uv.lock',
  'Pipfile.lock',
  'packages.lock.json',
  'Podfile.lock',
  'pubspec.lock',
  'flake.lock',
  'mix.lock',
  'Cartfile.resolved',
]);

/** Suffixes (lowercase) that mark a recorded expected output. */
const SNAPSHOT_SUFFIXES: readonly string[] = ['.snap', 'modelsnapshot.cs'];

/** Infixes (lowercase) that mark a recorded expected output, such as Foo.verified.txt. */
const SNAPSHOT_INFIXES: readonly string[] = ['.verified.', '.received.'];

/** Directory names that hold snapshots or fixtures. */
const SNAPSHOT_DIRECTORIES: ReadonlySet<string> = new Set(['__snapshots__']);
const FIXTURE_DIRECTORIES: ReadonlySet<string> = new Set(['fixtures', '__fixtures__']);

/** Suffixes (lowercase) that mark a file a tool wrote. */
const GENERATED_SUFFIXES: readonly string[] = [
  '.g.cs',
  '.g.vb',
  '.designer.cs',
  '.designer.vb',
  '.min.js',
  '.min.css',
  '.min.mjs',
  '.min.cjs',
  '.pb.cc',
  '.pb.h',
  '.pb.go',
  '_pb2.py',
  '_pb2.pyi',
  '_pb2_grpc.py',
];

/** Basename prefixes (lowercase) that mark a file a tool wrote. */
const GENERATED_PREFIXES: readonly string[] = ['zz_generated.'];

/** Infixes (lowercase) that mark a file a tool wrote, such as schema.generated.ts. */
const GENERATED_INFIXES: readonly string[] = ['.generated.'];

/** How many of the new side's head lines a generated marker is trusted on. */
const GENERATED_HEADER_HEAD_LINES = 3;

/** Markers of an auto-generated file, tested against the diff's visible lines. */
const GENERATED_HEADER_MARKERS: readonly RegExp[] = [
  /<auto-generated/i,
  /(?:^|[^a-z])@generated\b/i,
  /generated by .*do not edit/i,
  /do not edit.*generated by/i,
  /this file (?:is|was) (?:auto[- ]?generated|automatically generated|generated)/i,
];

/** One line per rule, stating what that rule can miss. */
const BLIND_SPOTS: Readonly<Record<string, string>> = {
  'rename-identical':
    'Identical content proves only the move; a move git reports as separate delete and add is missed.',
  'snapshot-name':
    'Only known snapshot names are matched; a snapshot under another name is read as ordinary source.',
  'fixture-path':
    'Only known fixture locations are matched; a fixture kept elsewhere is read as ordinary source.',
  'linguist-generated':
    'Attributes come from the root .gitattributes at the head commit; subdirectory .gitattributes files are not read.',
  'linguist-vendored':
    'Attributes come from the root .gitattributes at the head commit; subdirectory .gitattributes files are not read.',
  'lockfile-name':
    'Only known lockfile names are matched; a lockfile renamed or hand-written under another name is missed.',
  'generated-name':
    'Only known generated-file names are matched; a generated file under another name with no header in its diff is missed.',
  'generated-header':
    "Only a marker on the new side's first three lines is trusted; one deeper in the file is not, one above the first hunk is never seen, and unknown markers are missed.",
};

/** Labels that sink their part below the parts a reviewer must read. */
const SINKING_LABELS: ReadonlySet<string> = new Set([
  'lockfile',
  'generated',
  'vendored',
  'moved or renamed',
]);

/** The assessment carried by every part no rule covers (ADR 0001). */
const NO_RULE_APPLIED: NoiseAssessment = { label: 'none', note: 'no rule applied' };

function basename(path: string): string {
  return path.split('/').pop() ?? path;
}

/** Lowercase basename of the part's path, on the new side after any rename. */
function lowerBasename(part: Part): string {
  return basename(part.path).toLowerCase();
}

function hasAnySuffix(name: string, suffixes: readonly string[]): boolean {
  return suffixes.some((suffix) => name.endsWith(suffix));
}

/** True when any directory segment of the path is in the given set. */
function hasDirectory(path: string, directories: ReadonlySet<string>): boolean {
  return path.split('/').slice(0, -1).some((segment) => directories.has(segment));
}

/** The assessment a matched rule attaches: the labelled variant of NoiseAssessment. */
type LabelledNoise = Extract<NoiseAssessment, { label: NoiseLabel }>;

/**
 * A rename whose diff shows no other change — no edited lines, no mode
 * change, no differing binary content — proves identical content. A
 * renamed snapshot or fixture keeps its own label instead, because those
 * parts are never sunk: the test now reads its expectations under a new
 * name.
 */
function renameIdentical(part: Part): NoiseAssessment | undefined {
  if (
    part.changeKind !== 'rename' ||
    part.additions > 0 ||
    part.deletions > 0 ||
    part.isBinary ||
    part.oldMode !== part.newMode
  ) {
    return undefined;
  }
  const kept = snapshotName(part) ?? fixturePath(part);
  return {
    label: kept === undefined ? 'moved or renamed' : kept.label,
    rule: 'rename-identical',
    state: 'confirmed',
    blindSpot: BLIND_SPOTS['rename-identical']!,
  };
}

/** A recorded expected output: a test snapshot or a Verify file. */
function snapshotName(part: Part): LabelledNoise | undefined {
  const name = lowerBasename(part);
  if (
    !hasAnySuffix(name, SNAPSHOT_SUFFIXES) &&
    !SNAPSHOT_INFIXES.some((infix) => name.includes(infix)) &&
    !hasDirectory(part.path, SNAPSHOT_DIRECTORIES)
  ) {
    return undefined;
  }
  return {
    label: 'snapshot',
    rule: 'snapshot-name',
    state: 'claimed',
    blindSpot: BLIND_SPOTS['snapshot-name']!,
  };
}

/** Fixed input a test runs against, by directory or basename. */
function fixturePath(part: Part): LabelledNoise | undefined {
  const name = lowerBasename(part);
  if (!hasDirectory(part.path, FIXTURE_DIRECTORIES) && !name.includes('.fixture.')) {
    return undefined;
  }
  return {
    label: 'fixture',
    rule: 'fixture-path',
    state: 'claimed',
    blindSpot: BLIND_SPOTS['fixture-path']!,
  };
}

/** The repository's own linguist declaration, read at the head commit. */
function linguistLabel(attributes: LinguistAttributes): NoiseAssessment | undefined {
  if (attributes.vendored) {
    return {
      label: 'vendored',
      rule: 'linguist-vendored',
      state: 'claimed',
      blindSpot: BLIND_SPOTS['linguist-vendored']!,
    };
  }
  if (attributes.generated) {
    return {
      label: 'generated',
      rule: 'linguist-generated',
      state: 'claimed',
      blindSpot: BLIND_SPOTS['linguist-generated']!,
    };
  }
  return undefined;
}

/** A lock file or checksum file of the common ecosystems, by basename. */
function lockfileName(part: Part): NoiseAssessment | undefined {
  if (!LOCKFILE_BASENAMES.has(basename(part.path))) {
    return undefined;
  }
  return {
    label: 'lockfile',
    rule: 'lockfile-name',
    state: 'claimed',
    blindSpot: BLIND_SPOTS['lockfile-name']!,
  };
}

/** A file whose name says a tool wrote it. */
function generatedName(part: Part): NoiseAssessment | undefined {
  const name = lowerBasename(part);
  const matched =
    hasAnySuffix(name, GENERATED_SUFFIXES) ||
    GENERATED_PREFIXES.some((prefix) => name.startsWith(prefix)) ||
    GENERATED_INFIXES.some((infix) => name.includes(infix));
  if (!matched) {
    return undefined;
  }
  return {
    label: 'generated',
    rule: 'generated-name',
    state: 'claimed',
    blindSpot: BLIND_SPOTS['generated-name']!,
  };
}

/** A file whose head lines on the new side carry an auto-generated header. */
function generatedHeader(part: Part): NoiseAssessment | undefined {
  for (const hunk of part.hunks) {
    for (const line of hunk.lines) {
      if (line.kind === 'deletion') {
        continue; // Only lines the new side still carries prove the file.
      }
      const at = line.newLineNumber;
      if (at === undefined || at > GENERATED_HEADER_HEAD_LINES) {
        continue; // Only the file's head is trusted, as linguist reads it.
      }
      if (GENERATED_HEADER_MARKERS.some((marker) => marker.test(line.text.trim()))) {
        return {
          label: 'generated',
          rule: 'generated-header',
          state: 'claimed',
          blindSpot: BLIND_SPOTS['generated-header']!,
        };
      }
    }
  }
  return undefined;
}

/**
 * Assesses one part's noise: the first rule that matches attaches its
 * label with a state and a one-line blind spot, and when no rule matches
 * the assessment says so plainly (ADR 0001).
 *
 * `gitAttributes` is the repository's root `.gitattributes` as read at the
 * head commit, or null when the repository has none.
 */
export function assessNoise(
  part: Part,
  gitAttributes: string | null,
): NoiseAssessment {
  const linguist = gitAttributes === null ? undefined : linguistLabel(
    linguistAttributesFor(part.path, gitAttributes),
  );
  const assessment =
    renameIdentical(part) ??
    snapshotName(part) ??
    fixturePath(part) ??
    linguist ??
    lockfileName(part) ??
    generatedName(part) ??
    generatedHeader(part);
  return assessment ?? NO_RULE_APPLIED;
}

/**
 * Labels every part and sinks the noise to the bottom: the parts a
 * reviewer must read keep their diff order first, then the sinking noise
 * parts follow in theirs. Snapshots and fixtures are labelled but never
 * sunk, because a change there is a behaviour change.
 */
export function applyNoiseRules(parts: Part[], gitAttributes: string | null): Part[] {
  const labelled = parts.map((part) => ({ ...part, noise: assessNoise(part, gitAttributes) }));
  const readFirst = labelled.filter((part) => !part.noise || !SINKING_LABELS.has(part.noise.label));
  const sunkLast = labelled.filter((part) => part.noise && SINKING_LABELS.has(part.noise.label));
  return [...readFirst, ...sunkLast];
}
