import { describe, expect, it } from 'vitest';
import { applyNoiseRules, assessNoise } from '../src/noise.js';
import type { ChangeKind, Hunk, Part } from '../src/protocol.js';

/** A minimal part for the rules to judge; only what a rule reads matters. */
function part(
  overrides: Partial<
    Pick<Part, 'path' | 'previousPath' | 'changeKind' | 'isBinary' | 'oldMode' | 'newMode'>
  > & {
    hunks?: Hunk[];
  },
): Part {
  const additions = (overrides.hunks ?? []).flatMap((hunk) =>
    hunk.lines.filter((line) => line.kind === 'addition'),
  );
  const deletions = (overrides.hunks ?? []).flatMap((hunk) =>
    hunk.lines.filter((line) => line.kind === 'deletion'),
  );
  return {
    path: overrides.path ?? 'src/change.ts',
    previousPath: overrides.previousPath,
    changeKind: overrides.changeKind ?? ('modification' as ChangeKind),
    isBinary: overrides.isBinary ?? false,
    oldMode: overrides.oldMode,
    newMode: overrides.newMode,
    oldMissingFinalNewline: false,
    newMissingFinalNewline: false,
    hunks: overrides.hunks ?? [],
    additions: additions.length,
    deletions: deletions.length,
    // The noise rules never read the syntax findings; this is the neutral
    // value for a part that has not been through the syntax pass.
    syntax: { formattingOnly: { status: 'not-checked', reason: '' }, checksNotRun: [] },
  };
}

/** A hunk whose body is the given diff-prefixed lines. */
function hunk(body: string[]): Hunk {
  return {
    oldStart: 1,
    oldLines: body.filter((line) => line.startsWith(' ') || line.startsWith('-')).length,
    newStart: 1,
    newLines: body.filter((line) => line.startsWith(' ') || line.startsWith('+')).length,
    entities: [],
    lines: body.map((line) => ({
      kind: (line.startsWith('+')
        ? 'addition'
        : line.startsWith('-')
          ? 'deletion'
          : 'context') as Hunk['lines'][number]['kind'],
      oldLineNumber: line.startsWith('+') ? undefined : 1,
      newLineNumber: line.startsWith('-') ? undefined : 1,
      text: line.slice(1),
    })),
  };
}

describe('assessNoise', () => {
  it('labels a lockfile by name, claimed, with a blind spot', () => {
    for (const path of [
      'package-lock.json',
      'npm-shrinkwrap.json',
      'yarn.lock',
      'pnpm-lock.yaml',
      'bun.lock',
      'bun.lockb',
      'nested/Gemfile.lock',
      'Cargo.lock',
      'go.sum',
      'go.work.sum',
      'composer.lock',
      'poetry.lock',
      'uv.lock',
      'Pipfile.lock',
      'packages.lock.json',
      'Podfile.lock',
      'pubspec.lock',
      'flake.lock',
      'mix.lock',
      'Cartfile.resolved',
    ]) {
      const noise = assessNoise(part({ path }), null);
      expect(noise, path).toEqual({
        label: 'lockfile',
        rule: 'lockfile-name',
        state: 'claimed',
        blindSpot: expect.stringMatching(/\.\n?$/),
      });
    }
  });

  it('labels generated files by name, including the .NET patterns', () => {
    for (const path of [
      'src/Form1.g.cs',
      'src/NativeMethods.g.vb',
      'src/Form1.Designer.cs',
      'src/Settings.Designer.vb',
      'dist/bundle.min.js',
      'dist/site.min.css',
      'proto/user_pb2.py',
      'proto/user_pb2.pyi',
      'proto/user_pb2_grpc.py',
      'proto/user.pb.cc',
      'proto/user.pb.h',
      'proto/user.pb.go',
      'k8s/zz_generated.deepcopy.go',
      'api/schema.generated.ts',
    ]) {
      const noise = assessNoise(part({ path }), null);
      expect(noise, path).toEqual({
        label: 'generated',
        rule: 'generated-name',
        state: 'claimed',
        blindSpot: expect.any(String),
      });
    }
  });

  it('labels a file whose diff carries an auto-generated header', () => {
    for (const header of [
      '// <auto-generated />',
      "' <auto-generated>",
      '// @generated by fm',
      '# This file is automatically generated by the build.',
      '// Code generated by protoc-gen-go. DO NOT EDIT.',
      '// Generated by the tool. DO NOT EDIT.',
      '/* this file was auto-generated */',
    ]) {
      const noise = assessNoise(part({ path: 'src/handwritten.cs', hunks: [hunk([` ${header}`, '+let value = 1;'])] }), null);
      expect(noise, header).toEqual({
        label: 'generated',
        rule: 'generated-header',
        state: 'claimed',
        blindSpot: expect.any(String),
      });
    }
  });

  it('trusts a generated marker only on the new side head lines', () => {
    const headMarker: Hunk = {
      oldStart: 2,
      oldLines: 1,
      newStart: 3,
      newLines: 1,
      entities: [],
      lines: [
        {
          kind: 'context',
          oldLineNumber: 2,
          newLineNumber: 3,
          text: '# This file is automatically generated by the build.',
        },
      ],
    };
    expect(assessNoise(part({ path: 'src/handwritten.cs', hunks: [headMarker] }), null)).toEqual({
      label: 'generated',
      rule: 'generated-header',
      state: 'claimed',
      blindSpot: expect.any(String),
    });
    const deepMarker: Hunk = {
      oldStart: 38,
      oldLines: 1,
      newStart: 39,
      newLines: 1,
      entities: [],
      lines: [
        {
          kind: 'context',
          oldLineNumber: 38,
          newLineNumber: 39,
          text: '// a test that quotes <auto-generated /> in its prose',
        },
      ],
    };
    expect(assessNoise(part({ path: 'test/noise.test.ts', hunks: [deepMarker] }), null)).toEqual({
      label: 'none',
      note: 'no rule applied',
    });
  });

  it('does not label a file whose header appears only on the old side', () => {
    const noise = assessNoise(
      part({ path: 'src/now-handwritten.cs', hunks: [hunk(['-// <auto-generated />', '+// written by hand'])] }),
      null,
    );
    expect(noise).toEqual({ label: 'none', note: 'no rule applied' });
  });

  it('confirms a rename with identical content and keeps a one-line blind spot', () => {
    const noise = assessNoise(
      part({ path: 'src/new-place.ts', previousPath: 'src/old-place.ts', changeKind: 'rename' }),
      null,
    );
    expect(noise).toEqual({
      label: 'moved or renamed',
      rule: 'rename-identical',
      state: 'confirmed',
      blindSpot: expect.any(String),
    });
    expect((noise as { blindSpot: string }).blindSpot).not.toContain('\n');
  });

  it('keeps the snapshot label on a pure snapshot rename, confirmed, and never sinks it', () => {
    const noise = assessNoise(
      part({
        path: 'tests/__snapshots__/b.test.ts.snap',
        previousPath: 'tests/__snapshots__/a.test.ts.snap',
        changeKind: 'rename',
      }),
      null,
    );
    expect(noise).toEqual({
      label: 'snapshot',
      rule: 'rename-identical',
      state: 'confirmed',
      blindSpot: expect.any(String),
    });
    const ordered = applyNoiseRules(
      [
        part({ path: 'src/change.ts' }),
        part({
          path: 'tests/__snapshots__/b.test.ts.snap',
          previousPath: 'tests/__snapshots__/a.test.ts.snap',
          changeKind: 'rename',
        }),
        part({ path: 'package-lock.json' }),
      ],
      null,
    );
    expect(ordered.map((p) => p.path)).toEqual([
      'src/change.ts',
      'tests/__snapshots__/b.test.ts.snap',
      'package-lock.json',
    ]);
  });

  it('keeps the fixture label on a pure fixture rename, confirmed, and never sinks it', () => {
    const noise = assessNoise(
      part({
        path: 'tests/fixtures/renamed.json',
        previousPath: 'tests/fixtures/original.json',
        changeKind: 'rename',
      }),
      null,
    );
    expect(noise).toEqual({
      label: 'fixture',
      rule: 'rename-identical',
      state: 'confirmed',
      blindSpot: expect.any(String),
    });
    const ordered = applyNoiseRules(
      [
        part({ path: 'src/change.ts' }),
        part({
          path: 'tests/fixtures/renamed.json',
          previousPath: 'tests/fixtures/original.json',
          changeKind: 'rename',
        }),
      ],
      null,
    );
    expect(ordered.map((p) => p.path)).toEqual(['src/change.ts', 'tests/fixtures/renamed.json']);
  });

  it('does not confirm a rename that also changed the file mode', () => {
    const noise = assessNoise(
      part({
        path: 'bin/run.sh',
        previousPath: 'scripts/run.sh',
        changeKind: 'rename',
        oldMode: '100644',
        newMode: '100755',
      }),
      null,
    );
    expect(noise).toEqual({ label: 'none', note: 'no rule applied' });
  });

  it('does not confirm a binary rename whose bytes changed', () => {
    const noise = assessNoise(
      part({
        path: 'assets/icon.png',
        previousPath: 'assets/logo.png',
        changeKind: 'rename',
        isBinary: true,
      }),
      null,
    );
    expect(noise).toEqual({ label: 'none', note: 'no rule applied' });
  });

  it('does not treat edited lines inside a renamed file as noise', () => {
    const noise = assessNoise(
      part({
        path: 'src/settings.ts',
        previousPath: 'src/config.ts',
        changeKind: 'rename',
        hunks: [hunk([' context', '-removed during the rename', '+added during the rename'])],
      }),
      null,
    );
    expect(noise).toEqual({ label: 'none', note: 'no rule applied' });
  });

  it('labels a renamed lockfile with edits as a lockfile, not as a move', () => {
    const noise = assessNoise(
      part({
        path: 'sub/package-lock.json',
        previousPath: 'package-lock.json',
        changeKind: 'rename',
        hunks: [hunk(['-  "version": "1.0.0"', '+  "version": "1.0.1"'])],
      }),
      null,
    );
    expect(noise).toEqual({
      label: 'lockfile',
      rule: 'lockfile-name',
      state: 'claimed',
      blindSpot: expect.any(String),
    });
  });

  it('labels snapshots, including Verify and Entity Framework patterns', () => {
    for (const path of [
      'src/__snapshots__/review.test.ts.snap',
      'tests/anything.snap',
      'tests/ClassTests.verified.txt',
      'tests/ClassTests.verified.json',
      'tests/ClassTests.received.txt',
      'migrations/AppDbContextModelSnapshot.cs',
    ]) {
      const noise = assessNoise(part({ path }), null);
      expect(noise, path).toEqual({
        label: 'snapshot',
        rule: 'snapshot-name',
        state: 'claimed',
        blindSpot: expect.any(String),
      });
    }
  });

  it('labels fixtures by directory and by basename', () => {
    for (const path of [
      'src/__fixtures__/user.ts',
      'tests/fixtures/data.json',
      'deep/nested/fixtures/config.yaml',
      'tests/user.fixture.json',
    ]) {
      const noise = assessNoise(part({ path }), null);
      expect(noise, path).toEqual({
        label: 'fixture',
        rule: 'fixture-path',
        state: 'claimed',
        blindSpot: expect.any(String),
      });
    }
  });

  it('does not mistake a file whose name merely contains a directory word', () => {
    const noise = assessNoise(part({ path: 'src/fixtures.ts' }), null);
    expect(noise).toEqual({ label: 'none', note: 'no rule applied' });
  });

  it('honours linguist-generated and linguist-vendored from the head commit', () => {
    const attributes = ['src/generated/** linguist-generated=true', 'vendor/** linguist-vendored'].join(
      '\n',
    );
    expect(assessNoise(part({ path: 'src/generated/options.json' }), attributes)).toEqual({
      label: 'generated',
      rule: 'linguist-generated',
      state: 'claimed',
      blindSpot: expect.any(String),
    });
    expect(assessNoise(part({ path: 'vendor/lib/core.js' }), attributes)).toEqual({
      label: 'vendored',
      rule: 'linguist-vendored',
      state: 'claimed',
      blindSpot: expect.any(String),
    });
  });

  it('keeps a snapshot above a linguist-generated declaration that would sink it', () => {
    const attributes = '*.verified.txt linguist-generated=true';
    const noise = assessNoise(part({ path: 'tests/ClassTests.verified.txt' }), attributes);
    expect(noise).toEqual({
      label: 'snapshot',
      rule: 'snapshot-name',
      state: 'claimed',
      blindSpot: expect.any(String),
    });
  });

  it('says no rule applied when nothing matched', () => {
    expect(assessNoise(part({ path: 'src/change.ts' }), null)).toEqual({
      label: 'none',
      note: 'no rule applied',
    });
    expect(assessNoise(part({ path: 'src/change.ts' }), '*.vb linguist-generated=true')).toEqual({
      label: 'none',
      note: 'no rule applied',
    });
  });
});

describe('applyNoiseRules', () => {
  const parts = () => [
    part({ path: 'src/change.ts' }),
    part({ path: 'package-lock.json' }),
    part({ path: 'tests/anything.snap' }),
    part({ path: 'src/generated/options.json' }),
    part({
      path: 'src/new-place.ts',
      previousPath: 'src/old-place.ts',
      changeKind: 'rename',
    }),
    part({ path: 'tests/fixtures/data.json' }),
    part({ path: 'README.md' }),
  ];

  it('labels every part and sinks the noise to the bottom, keeping diff order', () => {
    const ordered = applyNoiseRules(parts(), null);

    expect(ordered.map((p) => p.path)).toEqual([
      'src/change.ts',
      'tests/anything.snap',
      'src/generated/options.json',
      'tests/fixtures/data.json',
      'README.md',
      'package-lock.json',
      'src/new-place.ts',
    ]);
  });

  it('never sinks a snapshot or a fixture, because a change there is a behaviour change', () => {
    for (const path of ['tests/anything.snap', 'tests/fixtures/data.json']) {
      const ordered = applyNoiseRules(
        [part({ path }), part({ path: 'src/change.ts' }), part({ path: 'package-lock.json' })],
        null,
      );
      expect(ordered.map((p) => p.path)[0], path).toBe(path);
    }
  });

  it('leaves the order alone when nothing is noise', () => {
    const quiet = [part({ path: 'a.ts' }), part({ path: 'b.ts' })];
    expect(applyNoiseRules(quiet, null).map((p) => p.path)).toEqual(['a.ts', 'b.ts']);
  });

  it('carries a one-line blind spot on every label', () => {
    for (const labelled of applyNoiseRules(parts(), null)) {
      const noise = labelled.noise!;
      if (noise.label === 'none') {
        expect(noise.note).toBe('no rule applied');
        continue;
      }
      expect(noise.blindSpot.length).toBeGreaterThan(0);
      expect(noise.blindSpot).not.toContain('\n');
      expect(['confirmed', 'claimed']).toContain(noise.state);
    }
  });
});
